[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=C:/Users/13950/Desktop/ea web demo/mysql-dev/data
port=3306
bind-address=127.0.0.1
character-set-server=utf8mb4
collation-server=utf8mb4_0900_ai_ci
default-storage-engine=INNODB

[client]
host=127.0.0.1
port=3306
default-character-set=utf8mb4
